lambda:
#  feedUrl: "http://rss.cnn.com/rss/edition.rss"
#  feedUrl: "http://rss.cnn.com/rss/edition_world.rss"
#  feedUrl: "http://rss.cnn.com/rss/edition_technology.rss"
#  feedUrl: "http://feeds.bbci.co.uk/news/england/london/rss.xml"
  feedUrl: "http://feeds.bbci.co.uk/news/politics/rss.xml"

azure:
  cosmos:
    uri: "https://lambda-db.documents.azure.com:443/"
    key: "dFexsoDGPdOi7kyKZOirB3lhHr1AgbgKdUNwoWOJZzpWoJayh25PoWB2Um6BxsGIyJX2ZRCjA6VL1oLGFIgnJQ=="
    secondaryKey: "ngsIvS15mRBSriI0ESZz8nqIwqROKsFFrNkHxvxM7QaehCkpLZzj8CvmG2ytyDzURjQ2VNSnXJpywH8UAr8FXA=="
    dbName: "feed_archive"
    queryMetricsEnabled: "true"

logging:
  level:
    com.azure.cosmos: INFO